# .travis.yml
language: node_js
node_js:
  - 10

install:
  - npm ci

jobs:
  include:
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: npm run prepare
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release